<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RayTraceApiPath Condition="'$(RayTraceApiPath)' == ''">$(MSBuildProjectDirectory)\libs\RayTraceApi.dll</RayTraceApiPath>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="CounterStrikeSharp.API" Version="1.0.371" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="RayTraceApi">
      <HintPath>$(RayTraceApiPath)</HintPath>
      <Private>false</Private>
    </Reference>
    <ProjectReference Include="..\..\shared\BotControllerApi\BotControllerApi.csproj">
      <Private>false</Private>
    </ProjectReference>
  </ItemGroup>

</Project>
